all:
	gcc main.c src/TST/tst.c src/menu.c src/PATRICIA/PATRICIA.c src/PATRICIA/Stats.c  -o main
production:
	gcc main.c src/TST/tst.c src/menu.c src/PATRICIA/PATRICIA.c src/PATRICIA/Stats.c  -o main
clean:
	rm main